# M.Amintoosi

In [46]:
from sklearn.cluster import KMeans
import numpy as np
X = np.array([[2,3,4,10,11,12,20,25,30]]).transpose()
kmeans = KMeans(n_clusters=3).fit(X)
kmeans.labels_

array([1, 1, 1, 2, 2, 2, 0, 0, 0])

In [45]:
kmeans.cluster_centers_

array([[ 3.],
       [25.],
       [11.]])

In [50]:
X = np.array([[1, 2], [1, 4], [1, 0],
              [10, 2], [10, 4], [10, 0]])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
kmeans.labels_

array([1, 1, 1, 0, 0, 0])

In [25]:
kmeans.cluster_centers_

array([[10.,  2.],
       [ 1.,  2.]])

In [52]:
kmeans.predict([[0, 0], [12, 3]])

array([1, 0])

In [ ]:
X